#
# [GeneralConfig]
#
class GeneralConfig:
    TIME_DELAY = 0.5
    SIGNAL_STRENGTH_TRHRESHOLD = 20
    RETRIES_WITHOUT_BEARER = 10
    RETRIES_WITHOUT_PLMN = 3
    RETRIES_WITHOUT_CONNECTION = 3
    RETRIES_WITHOUT_ADDRESS = 3
    RETRIES_WITHOUT_PING = 5
    TIME_DELAY_TO_RESET = 5