from enum import Enum


class StateMachineConfig(Enum):
    STATE_RESET_MODE = 10
    STATE_DISCONNECTED_MODE = 11
    STATE_CHECK_CONNECTED_MODE = 12
    STATE_CHECK_PACKET_SERVICE_MODE = 13
    STATE_CONFIGURE_DHCP_MODE = 14
    STATE_CONNECTED_MODE = 15
    STATE_INFO_MODE = 16
    

    TRANSICTION_RESET = 50
    TRANSICTION_CONNECT = 51
    TRANSICTION_CHECK_IS_CONNECTED = 52
    TRANSICTION_CHECK_HAS_PACKET_SERVICE = 53
    TRANSICTION_DISCONNECT = 54
    TRANSICTION_SET_DHCP = 55
    TRANSICTION_SET_INFO = 56

